# Orquestador global â€” modelo HCC (https://github.com/jurjoroa/hcc-website)
project:
  type: website
  resources:
    - assets/articulos
  render:
    - index.qmd
    - editores.qmd
    - sobre.qmd
    - observatorio.qmd
    - actualidad.qmd
    - contacto.qmd
    - investigacion
    - rvea
    - libro
    - docencia
    - servicios

metadata-files:
  - _website.yml
  - _format.yml
  - _brand.yml
